### ISSUE TITLE
Incorrect indent with YAML file

### ISSUE THREAD

**Issue by rtsui-harmonicinc** [gazugafan/vscode-indent-on-paste#24]
Expected behavior of pasted content
```
      - name: grafana-dashboard-nvidia-dcgm
        configMap:
          name: {{ DEPLOYMENT_NAME }}-grafana-dashboard-nvidia-dcgm
          defaultMode: 420
```

Actual Behavior
```
      - name: grafana-dashboard-nvidia-dcgm
      configMap:
        name: {{ DEPLOYMENT_NAME }}-grafana-dashboard-nvidia-dcgm
        defaultMode: 420
```
